# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_auto_20161122_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='friends.Users'),
        ),
    ]
