# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_friends_friend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.Users'),
        ),
    ]
